version: '3.9'
services:
  image_downloader:
    build: 
      context : .
      dockerfile : ./docker_download/dockerfile
    volumes:
      - ./images:/app/images
  image_extracter:
    build: 
      context : .
      dockerfile : ./docker_extract/dockerfile
    depends_on:
      - image_downloader
    volumes:
      - ./images:/app/images
      - ./metadata:/app/metadata
  image_analyse:
    build: 
      context : .
      dockerfile : ./docker_analyse/dockerfile
    depends_on:
      - image_extracter
    volumes:
      - ./images:/app/images
      - ./metadata:/app/metadata
  image_random:
    build:
      context: .
      dockerfile : ./docker_random/dockerfile
    depends_on:
      - image_analyse
    volumes:
      - ./images:/app/images
      - ./metadata:/app/metadata
      - ./prefered_image:/app/prefered_image

  
